#+TITLE: Verifiable Claims and Promise Theory

* Collaborators

Kate Sills 
Oliver Terbu   
Shahan Khatchadourian    
Zachary Larson 

* Abstract
One of the goals of modern day peer-to-peer systems is to build self-composing, self-organizing, distributed systems of cooperating agents. However, it is a challenge to describe self-organizing systems from a top-down perspective, since agents may choose to offer a variety of services or capabilities and the approach hides an agent's decision-making capabilities. A more reasonable alternative is to construct distributed systems using a bottom-up approach, whereby agents announce functions that they are willing to perform, and other agents can establish a commitment to receive such a service. Describing systems from a bottom-up approach thus enables reframing design perspectives on who is imposing vs offering the service. For this reason, we propose using Promise Theory, which advocates for agents to offer promises of services or credentials. A benefit of using promise theory is that promises can be used as a prerequisite to forming trust and certainty. We give two examples using promise theory in distributed systems: object capabilities and verifiable claims.


* References
  * Burgess, Mark: Thinking in Promises
https://en.wikipedia.org/wiki/Promise_theory
  * Verifiable Claims Data Model and Representations https://www.w3.org/TR/verifiable-claims-data-model/#general-characteristics